#
# Makefile for the Ft5336 touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_FT5336_TOUCHSCREEN_DRIVER)		+= ft5x06.o
ft5x06-objs 								+= ft5x06_ts.o
ft5x06-objs 								+= ft5x06_ex_fun.o
ft5x06-objs 								+= focaltech_ctl.o
ft5x06-objs 								+= mcap_test_lib.o
ft5x06-objs 								+= ini.o
